language: python

python:
    - "2.6"
    - "2.7"

sudo: false

env:
    - DJANGO=1.5.12 POSTGRES_TEST_USER=postgres POSTGRES_TEST_NAME=avocado MYSQL_TEST_USER=root MYSQL_TEST_NAME=avocado
    - DJANGO=1.6.10 POSTGRES_TEST_USER=postgres POSTGRES_TEST_NAME=avocado MYSQL_TEST_USER=root MYSQL_TEST_NAME=avocado
    - DJANGO=1.7.6 POSTGRES_TEST_USER=postgres POSTGRES_TEST_NAME=avocado MYSQL_TEST_USER=root MYSQL_TEST_NAME=avocado

services:
    - memcached
    - redis-server

addons:
    - postgres

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8==2.6.2
    - flake8

install:
    - pip install coverage Django==$DJANGO
    - pip install -r requirements.txt

before_script:
    - psql -U postgres -c 'CREATE DATABASE avocado;'
    - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS avocado;'

script:
    - coverage run test_suite.py --sqlite --mysql --postgres

after_success:
    - pip install -q coveralls
    - coveralls

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7.6 POSTGRES_TEST_USER=postgres POSTGRES_TEST_NAME=avocado MYSQL_TEST_USER=root MYSQL_TEST_NAME=avocado
