language: python

python:
    - "2.6"
    - "2.7"

env:
    - DJANGO=1.4.10
    - DJANGO=1.5.5

services:
    - memcache

before_install:
    - env | sort
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-yaml
    - git remote add upstream git://github.com/cbmi/avocado.git
    - upstream=master;
      if [ "$TRAVIS_PULL_REQUEST" != false ]; then
          upstream=$TRAVIS_BRANCH;
      fi;
      git fetch --append --no-tags upstream refs/heads/$upstream:refs/remotes/upstream/$upstream
    - /usr/bin/python bin/check_signoff.py

install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    flake8

script:
    - coverage run test_suite.py

after_success:
    - coveralls
